<a href="https://colab.research.google.com/github/jyotirangu/DataScience/blob/main/8_OOP_Concepts/OOP2_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1:Count number of instances of a class created in Python?
# Example: Say Car is any class.

# maruti = Car()
# bmw = Car()
# honda = Car()
# So after creating above instances. We want to count how many instances are created of Car class.

# For above example no of instances = 3.

# Write a program for above problem.

In [1]:
class Car:

  __count = 0 # private class variable

  def __init__(self):
    Car.__count += 1

  # When you define a method with the @classmethod decorator, Python
  # automatically passes the class (not the instance) as the first argument to
  # that method — and by convention, we call that first parameter cls. This allows
  #  you to access class-level variables and other class-level methods.

  @classmethod
  def get_count(cls):
        return cls.__count  # public class method to access count


maruti = Car()
bmw = Car()
honda = Car()

print("Number of Car instances created:", Car.get_count())

Number of Car instances created: 3


Q-2: Create a deck of cards class.

Internally, the deck of cards should use another class, a card class. Your requirements are:

The Deck class should have a deal method to deal a single card from the deck
After a card is dealt, it is removed from the deck.

There should be a shuffle method which makes sure the deck of cards has all 52 cards and then rearranges them randomly.

The Card class should have a suit (Hearts, Diamonds, Clubs, Spades) and a value (A,2,3,4,5,6,7,8,9,10,J,Q,K)


Deck Class

It is class of all possible cards in a deck. Total 52 cards.

Methods - deal() it will take out one card from the deck of cards.

Deck of cards should get shuffeled while creating the deck object.

no of cards remaining in deck - <number> should dsiplay on printing any deck object.


Card class

It is a class of card
Atrributes - suit and value
<suit> of <value> should dsiplay on printing any card object.

In [2]:
import random

class Card:

  def __init__(self, suit, value):
    self.suit = suit
    self.value = value

  def __repr__(self):
    return '{} of {}'.format(self.value, self.suit)


class Deck:

  def __init__(self):
    suits = ['Hearts','Diamonds','Clubs','Spades']
    values = ['A','2','3','4','5','6','7','8','9','10','J','K','Q']
    self.cards = [Card(suit,value) for suit in suits for value in values]
    # print(self.cards)

  def __str__(self):
    return "Cards left "+ str(len(self.cards))

  def shuffle(self):
    if len(self.cards) < 52:
      print('Only full deck can be shuffle')
    else:
      random.shuffle(self.cards)
    return self.cards

  def deal(self):
    if len(self.cards) == 0:
      print('All cards have been dealt')
    return self.cards.pop()

deck = Deck()
deck.shuffle()
print(deck.deal())
print(deck.deal())
print(deck)

6 of Clubs
7 of Clubs
Cards left 50


Q-3: Find the area of a rectangle.
Approach:

The class name should be Rectangle.

The constructor should accept two parameters length and height but you can't pass the values directly to it while creating the constructor.

E.g., rectangle = Rectangle(length=10, height=8) <-- you can't do that while creating the instances.

Create a method called area() which has no parameters.

Create a method called is_square() which also has no parameters. Return True if the rectangle is a square otherwise return False.

If you are using a if-else block inside the is_square() method, then use the one-linear syntax.

In [3]:
class Rectangle:
  def __init__(self):
    self.len = 0
    self.ht = 0
    self.set_dimension()


  def set_dimension(self):
    self.len = int(input('Enter the length : '))
    self.ht = int(input('Enter the height : '))


  def area(self):
    return self.len * self.ht

  def is_square(self):
    return True if self.len == self.ht else False


rect = Rectangle()
print("Area:", rect.area())
print("Is square?", rect.is_square())

Enter the length : 12
Enter the height : 12
Area: 144
Is square? True




Q-4: Problem 4
Statement: Write a program that uses datetime module within a class.

Enter manufacturing date and expiry date of the product.

The program must display the years, months and days that are left for expiry.

In [4]:
import datetime
from dateutil.relativedelta import relativedelta

class Product:

  def __init__(self):
    self.man_date = None
    self.exp_date = None
    self.details()
    self.expiry_info()

  def details(self):
    print('Enter the Manufacturing Date of the product : ')
    y1 = int(input('Year : '))
    m1 = int(input('Month : '))
    d1 = int(input('Date : '))
    self.man_date = datetime.date(y1,m1,d1)

    print('\nEnter the expiry date of the product : ')
    y2 = int(input('Year : '))
    m2 = int(input('Month : '))
    d2 = int(input('Date : '))
    self.exp_date = datetime.date(y2,m2,d2)

  def expiry_info(self):
    self.today = datetime.date.today()

    if self.exp_date < self.today:
      print("The product has already expired.")

    else:
      self.diff = relativedelta(self.exp_date,self.today)
      print('Time left for the expiry is {} years {} months {} days '.format(self.diff.years, self.diff.months, self.diff.days))

p = Product()

Enter the Manufacturing Date of the product : 
Year : 2021
Month : 12
Date : 23

Enter the expiry date of the product : 
Year : 2025
Month : 12
Date : 23
Time left for the expiry is 0 years 6 months 13 days 


Q-5: Problem 5
Statement: A university wants to automate their admission process.

Students are admitted based on the marks scored in the qualifying exam. A student is identified by student id, age and marks in qualifying exam.

Data are valid, if:

Age is greater than 20
Marks is between 0 and 100 (both inclusive)

A student qualifies for admission, if

Age and marks are valid and
Marks is 65 or more

Write a python program to represent the students seeking admission in the university.

In [5]:
class Student:

  def __init__(self):
    self.__id = None
    self.__marks = None
    self.__age = None

  # setter methods
  def set_id(self,id):
    self.__id = id
  def set_marks(self, marks):
    self.__marks = marks
  def set_age(self, age):
    self.__age = age

  # getters
  def get_id(self):
    return self.__id
  def get_marks(self):
    return self.__marks
  def get_age(self):
    return self.__age


  def age(self):
    return self.__age > 20

  def validate_marks(self):
    return self.__marks > 0 and self.__marks <= 100

  def check_qualification(self):
    if self.age() and self.validate_marks():
      return self.__marks >= 65
    else:
      return False

s1 = Student()
s1.set_id(101)
s1.set_age(21)
s1.set_marks(66)

print(s1.get_id())
print(s1.get_age())
print(s1.get_marks())

s1.check_qualification()

101
21
66


True

Q-6: Ice-Cream Scoops and Bowl shop
Create a class Scoop which has one public property flavor and one private proptery price.

Take flavor values during object creation.

Create a class Bowl with private prperty scoop_list which will have list of scoopd object.

Create a method add_scoops in Bowl class which will add any no of Scoop objects given as parameter and store it in scoops_list.

Make getter and setter method for price property.

Make a method display to display flavour and price of each Scoop in scoop_list and print total price of the bowl by adding all flavour scoops prices.

Make a method sold in both Scoop class and Bowl class to print no of quantity sold.

Ex.-

choco = Scoop('chocolate')

print(choco)

choco.set_price(100)

berry = Scoop('berry')

berry.set_price(120)

print(berry)

vanilla = Scoop('vanilla')

vanilla.set_price(150)

bowl = Bowl()

bowl.add_scoops(choco) # Giving one parameter

bowl.add_scoops(berry, vanilla) # Multiple

add_scoops should handle both scenerios
print(bowl)

bowl.display()

Scoop.sold()

Bowl.sold()

Output

Flavor - chocolate Price - None

Flavor - berry Price - 120

chocolate

berry

vanilla

Dsiplaying Bowl

Flavor - chocolate Price - 100

Flavor - berry Price - 120

Flavor - vanilla Price - 150

Price of Bowl - 370

3 scoops sold

1 bowls sold

In [6]:

class Scoop:

  __counter = 0

  def __init__(self,flavor):
    self.flavor = flavor
    self.__price = None
    Scoop.__counter += 1

  def set_price(self,price):
    self.__price = price

  def get_price(self):
    return self.__price

  def __str__(self):
    return "Flavor - {} and Price - {}".format(self.flavor,self.__price)

  @staticmethod
  def sold():
    return Scoop.__counter


class Bowl:

  __counter = 0

  def __init__(self):
    self.__scoop_list = []
    Bowl.__counter += 1

  @staticmethod
  def sold():
    return Bowl.__counter

  def add_scoops(self,*new_scoops):
    for scoop in new_scoops:
      self.__scoop_list.append(scoop)

  def display(self):
    total = 0
    for scoop in self.__scoop_list:
      print(scoop)
      total = total + scoop.get_price()

    print('Total price : ', total)


choco = Scoop('chocolate')
choco.set_price(100)

berry = Scoop('berry')
berry.set_price(120)

vanilla = Scoop('vanilla')
vanilla.set_price(150)

bowl = Bowl()

bowl.add_scoops(choco) # Giving one parameter
bowl.add_scoops(berry, vanilla) # Multiple
# add_scoops should handle both scenerios

bowl.display()

print(Scoop.sold())
print(Bowl.sold())

Flavor - chocolate and Price - 100
Flavor - berry and Price - 120
Flavor - vanilla and Price - 150
Total price :  370
3
1


Q-7:Ice-Cream Bowl continue..

Making advancement in the above classes. Scoop and Bowl

1. Introduce a property max_scoops in Bowl class to signify maximum scoops that a bowl can have, exceeding that it will display Bowl is full. Take default value as 3.

2. no_of_scoop in Scoop class with default value of 1

3. Print <flavour> added with every scoop added.

# Testing Code-1

choco = Scoop('chocolate', 1)

choco.set_price(100)

print(choco)


berry = Scoop('berry', 2)

berry.set_price(120)

print(berry)

vanilla = Scoop('vanilla') # no of scoop parameter not given, will take default value

vanilla.set_price(150)

print(vanilla)

Output:

Flavor - chocolate, No of Scoops - 1, Price - 100

Flavor - berry, No of Scoops - 2, Price - 120

Flavor - vanilla, No of Scoops - 1, Price - 150

Testing code-2 considering above test code executed

bowl1 = Bowl() # max_scoop parameter not given, will take default value

bowl1.add_scoops(choco) # Giving one parameter

bowl1.add_scoops(berry, vanilla) # Multiple

bowl1.display()

Output

chocolate added

berry added

Bowl is full

Dsiplaying Bowl-1

Flavor - chocolate, No of Scoops - 1, Price - 100

Flavor - berry, No of Scoops - 2, Price - 120

Price of Bowl-1: 340

Testing code-3, considering above tests executed

# Tetsing code-3

bowl2 = Bowl(2)

bowl2.add_scoops(berry)

bowl2.add_scoops(choco)


bowl2.display()

Bowl.sold()

Output:


berry added

chocolate not added. Bowl is full!!

Dsiplaying Bowl-2

Flavor - berry, No of Scoops - 2, Price - 120

Price of Bowl-2: 240

2 bowls sold

In [7]:

class Scoop:

  __counter = 0

  def __init__(self,flavor,num_scoops=1):
    self.flavor = flavor
    self.__price = None
    self.num_scoops = num_scoops
    Scoop.__counter += 1

  def set_price(self,price):
    self.__price = price

  def get_price(self):
    return self.__price

  def __str__(self):
    return "Flavor - {} and Price - {}".format(self.flavor,self.__price)

  @staticmethod
  def sold():
    return Scoop.__counter


class Bowl:

  __counter = 0

  def __init__(self,max_scoops=3):
    self.__scoop_list = []
    self.scoops_added = 0
    self.max_scoops = max_scoops
    Bowl.__counter += 1

  @staticmethod
  def sold():
    return Bowl.__counter

  def add_scoops(self,*new_scoops):
    for scoop in new_scoops:
      if self.scoops_added + scoop.num_scoops <= self.max_scoops:
        self.__scoop_list.append(scoop)
        self.scoops_added = self.scoops_added + scoop.num_scoops
        print(scoop.flavor,' added')
      else:
        print('Bowl is full')
        break


  def display(self):
    total = 0
    for scoop in self.__scoop_list:
      print(scoop)
      total = total + scoop.get_price()

    print('Total price : ', total)


choco = Scoop('chocolate', 1)
choco.set_price(100)
print(choco)


berry = Scoop('berry', 2)
berry.set_price(120)
print(berry)

vanilla = Scoop('vanilla') # no of scoop parameter not given, will take default value
vanilla.set_price(150)
print(vanilla)


bowl1 = Bowl() # max_scoop parameter not given, will take default value
bowl1.add_scoops(choco) # Giving one parameter
bowl1.add_scoops(berry, vanilla) # Multiple
bowl1.display()

Flavor - chocolate and Price - 100
Flavor - berry and Price - 120
Flavor - vanilla and Price - 150
chocolate  added
berry  added
Bowl is full
Flavor - chocolate and Price - 100
Flavor - berry and Price - 120
Total price :  220
